title: "Dr. Shaily Gandhi"
author: "Dr. Shaily Gandhi"
description: "Made by Dr. Shaily Gandhi"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home change"}
  - {file: "README.md", title: "About me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dr.shaily.gandhi@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ShailyGandhi"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/shaily-gandhi-ph-d-24285b85/"}
  - {title: X, icon: X, url: "https://x.com/ShailyGandhi"}
  - {title: ORCHID, icon: orchid, url: "https://orcid.org/0000-0002-8893-2130"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
